version: "3"
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: intern-mysql
    environment:
        MYSQL_ROOT_HOST: '%'
        MYSQL_DATABASE: intern-project
        MYSQL_USER: user
        MYSQL_PASSWORD: pass
        MYSQL_ROOT_PASSWORD: root_pass
    ports:
        - "4306:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - intern-data-storage:/var/lib/mysql
    networks:
      - common

  php:
    build: ./docker-local/php
    container_name: intern-php
    volumes:
      - ./source:/usr/share/source
      - ./docker-local/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    depends_on: ["db"]
    networks:
      - common

  nginx:
    image: nginx:latest
    volumes:
      - ./docker-local/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./source:/usr/share/source
    restart: always
    ports: ["8080:80"]
    depends_on: ["php"]
    networks:
      - common

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: intern-mysql
      PMA_USER: root
      PMA_PASSWORD: root_pass
      TZ: Asia/Tokyo
    ports:
      - '9003:80'
    depends_on: ["db"]
    networks:
      - common

volumes:
  intern-data-storage:
    driver: local

networks:
  common:
    driver: bridge
